# Generated by Django 3.1.3 on 2020-11-23 18:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201123_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 23, 18, 30, 24, 724626, tzinfo=utc)),
        ),
    ]
